version: '3'

services:
  postgres:
    image: postgres:11.1
    container_name: postgres
    domainname: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=resource
  sdb:
    build: ./
    container_name: 'my_docker_from_docker_compose'
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - spring.datasource.url=jdbc:postgresql://postgres:5432/resource